trigger:
- main

pool: local
steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
# - task: CopyFiles@2
#   inputs:
#     contents: '**/*.jar'
#     targetFolder: $(Build.ArtifactStagingDirectory)
# - script:     mvn deploy:deploy-file -Dfile=$(Build.ArtifactStagingDirectory)/mig/target/mig-1.0-SNAPSHOT.jar -DpomFile=mig/pom.xml -DrepositoryId=github -Durl=https://maven.pkg.github.com/balraj0017/java_ado -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true

- script: mvn deploy -Dmaven.wagon.http.ssl.allowall=true
  # script: mvn deploy:deploy-file -Dfile=$(Build.ArtifactStagingDirectory)/mig/target/mig-1.0-SNAPSHOT.jar -DpomFile=mig/pom.xml -DrepositoryId=github -Durl=https://maven.pkg.github.com/balraj0017/java_ado -Dtoken=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
  displayName: 'Publish Maven package to GitHub'
